/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIMain.java
 *
 * Created on 25-Aug-2011, 22:05:32
 */

package zzz_unused;


import rcm.phase2._1_EntityAnnotator_V3;
import rcm.phase2._2_EntityReader_V3;
import rcm.phase1._1_FeatureAnnotator;
import rcm.phase1._2_FeatureReader;
import rcm.phase1._3_StructurePredictor;
import java.awt.event.ItemEvent;
import zzz_unused.zzz_Mapping_V2;
import rcm.phase2._3_SemReg_V3_Populator;
import rcm.phase1._4_UIStyleSelector_V3;

/**
 *
 * @author Krish
 */
public class UIMain extends javax.swing.JFrame {
    String styleText = "";
    String ontologyText = "";
    String mappingText = "";

    /** Creates new form UIMain */
    public UIMain() {
        super();
        initComponents();
        setVisible(true);
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFeatureAnnotator = new javax.swing.JCheckBox();
        cbStructurePredictor = new javax.swing.JCheckBox();
        cbFeatureReader = new javax.swing.JCheckBox();
        cbStyleSelector = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnStyleProcessing = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbEntityAnnotator = new javax.swing.JCheckBox();
        cbSemregPopulator = new javax.swing.JCheckBox();
        cbOntoregPopulator = new javax.swing.JCheckBox();
        cbEntityExtractor = new javax.swing.JCheckBox();
        btnOntologyPopulation = new javax.swing.JButton();
        lblSection1 = new javax.swing.JLabel();
        lblSection2 = new javax.swing.JLabel();
        cbOther2 = new javax.swing.JCheckBox();
        cbOther1 = new javax.swing.JCheckBox();
        lblSection3 = new javax.swing.JLabel();
        cbTaskAnnotation = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        btnMapping = new javax.swing.JButton();
        cbMapping = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taStyle = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMapping = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taOntology = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        cbFeatureAnnotator.setBackground(new java.awt.Color(0, 204, 204));
        cbFeatureAnnotator.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbFeatureAnnotator.setLabel("Feature Annotator");
        cbFeatureAnnotator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFeatureAnnotatorItemStateChanged(evt);
            }
        });
        cbFeatureAnnotator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFeatureAnnotatorActionPerformed(evt);
            }
        });

        cbStructurePredictor.setBackground(new java.awt.Color(0, 204, 204));
        cbStructurePredictor.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbStructurePredictor.setLabel("Structure Predictor");
        cbStructurePredictor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStructurePredictorItemStateChanged(evt);
            }
        });

        cbFeatureReader.setBackground(new java.awt.Color(0, 204, 204));
        cbFeatureReader.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbFeatureReader.setText("Feature Reader");
        cbFeatureReader.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFeatureReaderItemStateChanged(evt);
            }
        });

        cbStyleSelector.setBackground(new java.awt.Color(0, 204, 204));
        cbStyleSelector.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbStyleSelector.setLabel("Style Selector (GUI)");
        cbStyleSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStyleSelectorItemStateChanged(evt);
            }
        });

        btnStyleProcessing.setText("Process  Style Processing Tasks");
        btnStyleProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStyleProcessingActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Impact", 0, 48));
        lblTitle.setText("RegCMantic Main Window");

        cbEntityAnnotator.setBackground(new java.awt.Color(0, 204, 204));
        cbEntityAnnotator.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbEntityAnnotator.setText("Entity Annotator");
        cbEntityAnnotator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEntityAnnotatorItemStateChanged(evt);
            }
        });

        cbSemregPopulator.setBackground(new java.awt.Color(0, 204, 204));
        cbSemregPopulator.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbSemregPopulator.setText("SemReg Ontology Populator");
        cbSemregPopulator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSemregPopulatorItemStateChanged(evt);
            }
        });

        cbOntoregPopulator.setBackground(new java.awt.Color(0, 204, 204));
        cbOntoregPopulator.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbOntoregPopulator.setText("OntoReg Ontology Populator ");
        cbOntoregPopulator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOntoregPopulatorItemStateChanged(evt);
            }
        });

        cbEntityExtractor.setBackground(new java.awt.Color(0, 204, 204));
        cbEntityExtractor.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbEntityExtractor.setText("Entity Reader");
        cbEntityExtractor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEntityReaderItemStateChanged(evt);
            }
        });

        btnOntologyPopulation.setText("Process  Ontology Population Tasks");
        btnOntologyPopulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOntologyPopulationActionPerformed(evt);
            }
        });

        lblSection1.setBackground(new java.awt.Color(204, 204, 204));
        lblSection1.setFont(new java.awt.Font("Impact", 0, 24));
        lblSection1.setForeground(new java.awt.Color(51, 51, 51));
        lblSection1.setText("Style Processing Tasks");

        lblSection2.setBackground(new java.awt.Color(204, 204, 204));
        lblSection2.setFont(new java.awt.Font("Impact", 0, 24));
        lblSection2.setForeground(new java.awt.Color(51, 51, 51));
        lblSection2.setText("SemReg Ontology Polulation Tasks");

        cbOther2.setBackground(new java.awt.Color(0, 204, 204));
        cbOther2.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbOther2.setText("Other 2 : ");
        cbOther2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOther2ItemStateChanged(evt);
            }
        });

        cbOther1.setBackground(new java.awt.Color(0, 204, 204));
        cbOther1.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbOther1.setText("Other 1 :");
        cbOther1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOther1ItemStateChanged(evt);
            }
        });

        lblSection3.setBackground(new java.awt.Color(204, 204, 204));
        lblSection3.setFont(new java.awt.Font("Impact", 0, 24));
        lblSection3.setForeground(new java.awt.Color(51, 51, 51));
        lblSection3.setText("Mapping and Other Tasks");

        cbTaskAnnotation.setBackground(new java.awt.Color(0, 204, 204));
        cbTaskAnnotation.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbTaskAnnotation.setText("Validation Task Annotation");
        cbTaskAnnotation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTaskAnnotationItemStateChanged(evt);
            }
        });

        btnMapping.setText("Process All Mapping Tasks");
        btnMapping.setActionCommand("Process Mapping Tasks");
        btnMapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMappingActionPerformed(evt);
            }
        });

        cbMapping.setBackground(new java.awt.Color(0, 204, 204));
        cbMapping.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbMapping.setText("Mapping");
        cbMapping.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMappingItemStateChanged(evt);
            }
        });

        taStyle.setColumns(20);
        taStyle.setRows(5);
        jScrollPane1.setViewportView(taStyle);

        taMapping.setColumns(20);
        taMapping.setRows(5);
        jScrollPane2.setViewportView(taMapping);

        taOntology.setColumns(20);
        taOntology.setRows(5);
        jScrollPane4.setViewportView(taOntology);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbOther1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSection3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMapping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTaskAnnotation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(cbOther2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMapping, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSection2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSemregPopulator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbEntityExtractor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbEntityAnnotator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addComponent(cbOntoregPopulator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSection1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbStructurePredictor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFeatureReader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFeatureAnnotator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addComponent(cbStyleSelector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStyleProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOntologyPopulation)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSection1)
                    .addComponent(btnStyleProcessing))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbFeatureAnnotator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbFeatureReader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStructurePredictor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStyleSelector)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSection2)
                    .addComponent(btnOntologyPopulation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbEntityAnnotator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEntityExtractor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSemregPopulator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOntoregPopulator))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSection3)
                    .addComponent(btnMapping))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbTaskAnnotation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMapping)
                        .addGap(40, 40, 40)
                        .addComponent(cbOther1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOther2))
                    .addComponent(jScrollPane2))
                .addGap(54, 54, 54))
        );

        btnStyleProcessing.getAccessibleContext().setAccessibleName("Process");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFeatureAnnotatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFeatureAnnotatorActionPerformed

        
    }//GEN-LAST:event_cbFeatureAnnotatorActionPerformed

    private void btnStyleProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStyleProcessingActionPerformed
        styleText = "";
        if (featureAnnotator){
            new _1_FeatureAnnotator();
            styleText += "... feature annotation COMPLETED !!! \n";
            taStyle.setText(styleText);
        }
        if (featureReader){
            new _2_FeatureReader();
            styleText += "... feature reading COMPLETED !!! \n";
            taStyle.setText(styleText);
        }
        if (structurePredictor){
            new _3_StructurePredictor();
            styleText += "... structure prediction COMPLETED !!! \n";
            taStyle.setText(styleText);
        }
        if (styleSelector){
            new _4_UIStyleSelector_V3();
            styleText += "... style selection COMPLETED !!! \n";
            taStyle.setText(styleText);
        }
        
        
    }//GEN-LAST:event_btnStyleProcessingActionPerformed

    private void btnOntologyPopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOntologyPopulationActionPerformed
        ontologyText = "";
        if (entityAnnotator){
            new _1_EntityAnnotator_V3();
            ontologyText += "... entity annotation COMPLETED !!! \n";
            taOntology.setText(ontologyText);
        }
        if (entityReader){
            new _2_EntityReader_V3();
            ontologyText += "... entity reading COMPLETED !!! \n";
            taOntology.setText(ontologyText);
        }
        if (semregPopulator){
            new _3_SemReg_V3_Populator();
            ontologyText += "... SemReg ontology population COMPLETED !!! \n";
            taOntology.setText(ontologyText);
        }
        if (ontoregPopulator){
            new OntoReg_V2_Populator();
            ontologyText += "... OntoReg ontology population COMPLETED !!! \n";
            taOntology.setText(ontologyText);
        }
    }//GEN-LAST:event_btnOntologyPopulationActionPerformed

    private void btnMappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMappingActionPerformed
        mappingText = "";
        if (taskAnnotator){
            new TaskAnnotator();
            mappingText += "... task annotation COMPLETED !!! \n";
            taMapping.setText(styleText);
        }
        if (mapping){
            new zzz_Mapping_V2();
            mappingText += "... mapping  COMPLETED !!! \n";
            taMapping.setText(mappingText);
        }
        if (other1){

            mappingText += "... other1 COMPLETED !!! \n";
            taMapping.setText(mappingText);
        }
        if (other2){

            mappingText += "... other2 COMPLETED !!! \n";
            taMapping.setText(mappingText);
        }
    }//GEN-LAST:event_btnMappingActionPerformed

    private void cbFeatureAnnotatorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFeatureAnnotatorItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED){
            styleText += "Feature annotation SELECTED \n";
            taStyle.setText(styleText);
            featureAnnotator = true;
        } else {
            styleText += "x... Feature annotation UNSELECTED \n";
            taStyle.setText(styleText);
            featureAnnotator = false;
        }
    }//GEN-LAST:event_cbFeatureAnnotatorItemStateChanged

    private void cbFeatureReaderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFeatureReaderItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            styleText += "Feature reader SELECTED \n";
            taStyle.setText(styleText);
            featureReader = true;
        } else {
            styleText += "x... Feature reader UNSELECTED \n";
            taStyle.setText(styleText);
            featureReader = false;
        }
    }//GEN-LAST:event_cbFeatureReaderItemStateChanged

    private void cbStructurePredictorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStructurePredictorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            styleText += "Structure predictor SELECTED \n";
            taStyle.setText(styleText);
            structurePredictor = true;
        } else {
            styleText += "x... Structure predictor UNSELECTED \n";
            taStyle.setText(styleText);
            structurePredictor = false;
        }
    }//GEN-LAST:event_cbStructurePredictorItemStateChanged

    private void cbStyleSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStyleSelectorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            styleText += "Style selection SELECTED \n";
            taStyle.setText(styleText);
            styleSelector = true;
        } else {
            styleText += "x... Style selection UNSELECTED \n";
            taStyle.setText(styleText);
            styleSelector = false;
        }
    }//GEN-LAST:event_cbStyleSelectorItemStateChanged

    private void cbEntityAnnotatorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEntityAnnotatorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            ontologyText += "Entity annotation SELECTED \n";
            taOntology.setText(ontologyText);
            entityAnnotator = true;
        } else {
            ontologyText += "x... entity annotation UNSELECTED \n";
            taOntology.setText(ontologyText);
            entityAnnotator = false;
        }
    }//GEN-LAST:event_cbEntityAnnotatorItemStateChanged

    private void cbEntityReaderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEntityReaderItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            ontologyText += "Entity reading SELECTED \n";
            taOntology.setText(ontologyText);
            entityReader = true;
        } else {
            ontologyText += "x... entity reading UNSELECTED \n";
            taOntology.setText(ontologyText);
            entityReader = false;
        }
    }//GEN-LAST:event_cbEntityReaderItemStateChanged

    private void cbSemregPopulatorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSemregPopulatorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            ontologyText += "SemReg ontology populator SELECTED \n";
            taOntology.setText(ontologyText);
            semregPopulator = true;
        } else {
            ontologyText += "x... SemReg ontology populator UNSELECTED \n";
            taOntology.setText(ontologyText);
            semregPopulator = false;
        }
    }//GEN-LAST:event_cbSemregPopulatorItemStateChanged

    private void cbOntoregPopulatorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOntoregPopulatorItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED){
            ontologyText += "OntoReg ontology populator SELECTED \n";
            taOntology.setText(ontologyText);
            ontoregPopulator = true;
        } else {
            ontologyText += "x... OntoReg ontology populator UNSELECTED \n";
            taOntology.setText(ontologyText);
            ontoregPopulator = false;
        }
    }//GEN-LAST:event_cbOntoregPopulatorItemStateChanged

    private void cbTaskAnnotationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTaskAnnotationItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            mappingText += "Task annotator SELECTED \n";
            taMapping.setText(mappingText);
            taskAnnotator = true;
        } else {
            mappingText += "x... task annotator UNSELECTED \n";
            taMapping.setText(mappingText);
            taskAnnotator = false;
        }
    }//GEN-LAST:event_cbTaskAnnotationItemStateChanged

    private void cbMappingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMappingItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED){
           mappingText += "Mapping SELECTED \n";
            taMapping.setText(styleText);
            mapping = true;
        } else {
            mappingText += "x... mapping UNSELECTED \n";
            taMapping.setText(mappingText);
            mapping = false;
        }
    }//GEN-LAST:event_cbMappingItemStateChanged

    private void cbOther1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOther1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            mappingText += "Other1 SELECTED \n";
            taMapping.setText(mappingText);
            other1 = true;
        } else {
            mappingText += "x... other1 UNSELECTED \n";
            taMapping.setText(mappingText);
            other1 = false;
        }
    }//GEN-LAST:event_cbOther1ItemStateChanged

    private void cbOther2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOther2ItemStateChanged
       if (evt.getStateChange() == ItemEvent.SELECTED){
            mappingText += "Other2 SELECTED \n";
            taMapping.setText(mappingText);
            other2 = true;
        } else {
            mappingText += "x... other2 UNSELECTED \n";
            taMapping.setText(mappingText);
            other2 = false;
        }
    }//GEN-LAST:event_cbOther2ItemStateChanged

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIMain().setVisible(true);
            }
        });
    }
     *
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMapping;
    private javax.swing.JButton btnOntologyPopulation;
    private javax.swing.JButton btnStyleProcessing;
    private javax.swing.JCheckBox cbEntityAnnotator;
    private javax.swing.JCheckBox cbEntityExtractor;
    private javax.swing.JCheckBox cbFeatureAnnotator;
    private javax.swing.JCheckBox cbFeatureReader;
    private javax.swing.JCheckBox cbMapping;
    private javax.swing.JCheckBox cbOntoregPopulator;
    private javax.swing.JCheckBox cbOther1;
    private javax.swing.JCheckBox cbOther2;
    private javax.swing.JCheckBox cbSemregPopulator;
    private javax.swing.JCheckBox cbStructurePredictor;
    private javax.swing.JCheckBox cbStyleSelector;
    private javax.swing.JCheckBox cbTaskAnnotation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblSection1;
    private javax.swing.JLabel lblSection2;
    private javax.swing.JLabel lblSection3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea taMapping;
    private javax.swing.JTextArea taOntology;
    private javax.swing.JTextArea taStyle;
    // End of variables declaration//GEN-END:variables

    /* Style processing related */
    private boolean featureAnnotator = false;
    private boolean featureReader = false;
    private boolean structurePredictor = false;
    private boolean styleSelector = false;

    /*  Ontologies population related */
    private boolean entityAnnotator = false;
    private boolean entityReader = false;
    private boolean semregPopulator = false;
    private boolean ontoregPopulator = false;

    /*  Mapping and others related */
    private boolean taskAnnotator = false;
    private boolean mapping = false;
    private boolean other1= false;
    private boolean other2 = false;


}
